### ISSUE TITLE
bug: Warpcast login does not work.

### ISSUE THREAD

**Issue by hskang9** [farcasterxyz/contracts#412]
**What is the bug?**
API did not handle undefined fetch error

**How can it be reproduced? (optional)**
I can only show copy of debugging error, but it says the map function in Farcaster api is undefined.

```
{
  "error": "\n######################################################################\n\nUnhandledFetchError\n...message: Cannot read property 'map' of undefined\n...name: Farcaster API Error\n...absoluteUrl: https://client.warpcast.com/v2/client-config\n...body: undefined\n...endpointName: getClientConfig\n...hasTimedOut: false\n...isNetworkError: false\n...method: GET\n...relativeUrl: /v2/client-config\n...resolvedTimeout: 20000\n...response: [object Object]\n...responseData: undefined\n...status: 403\n...timeout: undefined\n...componentStack: \n    in Unknown\n    in Unknown\n    in InvalidateAndPurgeQueryCachesOnStartup\n    in Unknown\n    in ErrorBoundary\n    in QueryErrorResetBoundary\n    in RetryableErrorBoundary\n    in QueryClientProvider\n    in Suspense\n    in RNCSafeAreaProvider\n    in SafeAreaProvider\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in AndroidNavigationBarColor\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in AnalyticsEnabledProvider\n    in Unknown\n    in Unknown\n    in Unknown\n    in Unknown\n    in ErrorBoundary\n    in DebugLogsProvider\n    in ErrorHistoryProvider\n    in Unknown\n    in RCTView\n    in Unknown\n    in __Sentry.TouchEventBoundary\n    in WithTouchEventBoundary\n    in ReactNativeProfiler\n    in RCTView\n    in Unknown\n    in __Sentry.TouchEventBoundary\n    in RootApp\n    in RCTView\n    in Unknown\n    in GestureHandlerRootView\n    in gestureHandlerRootHOC(RootApp)\n    in RCTView\n    in Unknown\n    in RCTView\n    in Unknown\n    in AppContainer\n...isComponentError: true\n...unwrappedErrorMessage: Cannot read property 'map' of undefined\n...unwrappedErrorStack: TypeError: Cannot read property 'map' of undefined\n    at ?anon_0_ (/Users/expo/Library/Developer/Xcode/DerivedData/Warpcast-egwbacudxudaekghlqpvuosfbqxx/Build/Intermediates.noindex/ArchiveIntermediates/Warpcast/BuildProductsPath/Release-iphoneos/main.jsbundle:183951:85)\n    at next (native)\n    at asyncGeneratorStep (/Users/expo/Library/Developer/Xcode/DerivedData/Warpcast-egwbacudxudaekghlqpvuosfbqxx/Build/Intermediates.noindex/ArchiveIntermediates/Warpcast/BuildProductsPath/Release-iphoneos/main.jsbundle:44033:26)\n    at _next (/Users/expo/Library/Developer/Xcode/DerivedData/Warpcast-egwbacudxudaekghlqpvuosfbqxx/Build/Intermediates.noindex/ArchiveIntermediates/Warpcast/BuildProductsPath/Release-iphoneos/main.jsbundle:44052:29)\n    at tryCallOne (/Users/expo/Library/Developer/Xcode/DerivedData/Warpcast-egwbacudxudaekghlqpvuosfbqxx/Build/Intermediates.noindex/ArchiveIntermediates/Warpcast/BuildProductsPath/Release-iphoneos/main.jsbundle:15715:16)\n    at anonymous (/Users/expo/Library/Developer/Xcode/DerivedData/Warpcast-egwbacudxudaekghlqpvuosfbqxx/Build/Intermediates.noindex/ArchiveIntermediates/Warpcast/BuildProductsPath/Release-iphoneos/main.jsbundle:15796:27)\n    at apply (native)\n    at anonymous (/Users/expo/Library/Developer/Xcode/DerivedData/Warpcast-egwbacudxudaekghlqpvuosfbqxx/Build/Intermediates.noindex/ArchiveIntermediates/Warpcast/BuildProductsPath/Release-iphoneos/main.jsbundle:16933:26)\n    at _callTimer (/Users/expo/Library/Developer/Xcode/DerivedData/Warpcast-egwbacudxudaekghlqpvuosfbqxx/Build/Intermediates.noindex/ArchiveIntermediates/Warpcast/BuildProductsPath/Release-iphoneos/main.jsbundle:16822:17)\n    at _callReactNativeMicrotasksPass (/Users/expo/Library/Developer/Xcode/DerivedData/Warpcast-egwbacudxudaekghlqpvuosfbqxx/Build/Intermediates.noindex/ArchiveIntermediates/Warpcast/BuildProductsPath/Release-iphoneos/main.jsbundle:16860:17)\n    at callReactNativeMicrotasks (/Users/expo/Library/Developer/Xcode/DerivedData/Warpcast-egwbacudxudaekghlqpvuosfbqxx/Build/Intermediates.noindex/ArchiveIntermediates/Warpcast/BuildProductsPath/Release-iphoneos/main.jsbundle:17063:44)\n    at __callReactNativeMicrotasks (/Users/expo/Library/Developer/Xcode/DerivedData/Warpcast-egwbacudxudaekghlqpvuosfbqxx/Build/Intermediates.noindex/ArchiveIntermediates/Warpcast/BuildProductsPath/Release-iphoneos/main.jsbundle:2712:46)\n    at anonymous (/Users/expo/Library/Developer/Xcode/DerivedData/Warpcast-egwbacudxudaekghlqpvuosfbqxx/Build/Intermediates.noindex/ArchiveIntermediates/Warpcast/BuildProductsPath/Release-iphoneos/main.jsbundle:2577:45)\n    at __guard (/Users/expo/Library/Developer/Xcode/DerivedData/Warpcast-egwbacudxudaekghlqpvuosfbqxx/Build/Intermediates.noindex/ArchiveIntermediates/Warpcast/BuildProductsPath/Release-iphoneos/main.jsbundle:2685:15)\n    at flushedQueue (/Users/expo/Library/Developer/Xcode/DerivedData/Warpcast-egwbacudxudaekghlqpvuosfbqxx/Build/Intermediates.noindex/ArchiveIntermediates/Warpcast/BuildProductsPath/Release-iphoneos/main.jsbundle:2576:21)\n    at invokeCallbackAndReturnFlushedQueue (/Users/expo/Library/Developer/Xcode/DerivedData/Warpcast-egwbacudxudaekghlqpvuosfbqxx/Build/Intermediates.noindex/ArchiveIntermediates/Warpcast/BuildProductsPath/Release-iphoneos/main.jsbundle:2570:33)\n\n######################################################################\n",
  "localTimestamp": 1713277342629,
  "unauthed": true
}
```

**Additional context (optional)**
It worked yesterday.

**Comment by Aliakbar57** [comment]
I'm completed payment transition purchased warpcast I'd payment transition completed through Google transition yesterday morning until not active my warpcast app not supported further process
I have transition id and screen shot transition purchased warpcast proof plz active app for fruther process or chat with me

**Comment by Cryptoption8924** [comment]
I've finished the payment and signed up, but I can't log in. It keeps showing a "debug error" message. I've already reached out to Varun on Twitter about this. Could you please look into and resolve this issue?

**Comment by Tekus01** [comment]
![IMG_2474](https://github.com/farcasterxyz/contracts/assets/145226776/51e184f3-00da-4de3-aea8-a84624387c2f)

I get this error opening the app, please help

**Comment by san-caitian** [comment]
![WechatIMG475](https://github.com/farcasterxyz/contracts/assets/83528476/dd8aa0f1-13b6-487f-91bc-62516b1e208b)
me too.What should I do if I change it?

**Comment by san-caitian** [comment]
> ![IMG_2474](https://private-user-images.githubusercontent.com/145226776/338763589-51e184f3-00da-4de3-aea8-a84624387c2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTgzODksIm5iZiI6MTcxODM1ODA4OSwicGF0aCI6Ii8xNDUyMjY3NzYvMzM4NzYzNTg5LTUxZTE4NGYzLTAwZGEtNGRlMy1hZWE4LWE4NDYyNDM4N2MyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQwOTQxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjQzYTVmY2ZkYTZkYmRiNDQ2YjQxOGJkMjUxODYyZDdkOTU3ZGU0YWQ5MWE3NThmYzI5ODQ2MTk4MjhmYzBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zwfnfxaHQytSVSFsSVpgbfggJCwBj3qRb3wRPJuVehI)
> 
> 我打开应用程序时出现此错误，请帮忙
me too,What should I do if I change it?

**Comment by Anexstar** [comment]
Hi warpcast
...
I have purchased my farcaster logins but my phone got formatted and I can't login back toy account on my phone.. it keeps bringing up a red error message ..
Pls help me I need help... I have my secret phrase.. and tried using it to login to my warpcast account but to no avail...

Pls help me... I don't have money to pay for another login...

Thanks ..  hope you hear from you soon

**Comment by Darmawansah** [comment]
{
  "error": "\n######################################################################\n\nHandledFetchError\n...message: getOnboardingState 403 - No active Warpcast signer exists for FID undefined\n...name: Farcaster API Error\n...absoluteUrl: https://client.warpcast.com/v2/onboarding-state\n...body: undefined\n...endpointName: getOnboardingState\n...hasTimedOut: false\n...isNetworkError: false\n...method: GET\n...relativeUrl: /v2/onboarding-state\n...resolvedTimeout: 20000\n...response: [object Object]\n...responseData: [object Object]\n...status: 403\n...timeout: undefined\n\n######################################################################\n",
  "localTimestamp": 1719613743190,
  "unauthed": true
}

**Comment by imtipi** [comment]
same,warpcast can't import a FID that isn't registered at warpcast,cause my can't use my old FID at all

**Comment by antonbarada** [comment]
++

**Comment by Sh1Tt** [comment]
Signed up, paid., can't login, please help

**Comment by varunsrin** [comment]
will investigate this one.

**Comment by cartist00** [comment]
Thank you!

I've been trying to reach you or someone from the Warpcast team for the
past few days. I spoke with Ted in DMs yesterday, and she mentioned that
everything should be fixed. I got logged out of the desktop version but was
able to log back in using the email I provided to her. However, when I
tried the same on my phone, nothing worked.


My fid : 354255

**Comment by cartist00** [comment]
I've decided to completely leave this app for about a week or more since my account issue still hasn't been resolved. I've received two emails from Warpcast saying my account recovery is complete, but in reality, it's not!
I deleted the app for now and will come back to it later. This is just taking up too much time and effort, and in the end, nothing gets fixed!

I’ve done everything on my end - backed up the seed phrase, ensured the email is correct - I'm not sure what else I can do! It seems like the issue is on their side,  the phone app just isn't working properly, and I am not the only one who's saying that! 

My email address is not going through, it's showing as unavailable! Could the team please check on their side to confirm if this email is correct?

This is my account information,

FID : 354255
Email : laurabalbarde19@gmail.com

Check the screenshot!

![Image](https://github.com/user-attachments/assets/a29e13d0-4829-442e-9f57-e15186905ba5)

**Comment by Khunlle** [comment]
I recently subscribed to Warpcast, but I am unable to complete my profile setup. Every time I try, I receive an error message stating, "There was a problem creating your account." I have attempted multiple troubleshooting steps, including restarting the app, checking my internet connection, and clearing the cache, but the issue persists.

My payment was successfully processed, and I would appreciate any assistance in resolving this issue as soon as possible. Please let me know if you need any additional details from me.

Looking forward to your prompt response.

My mail aderogbaadekunle10@gmail.coma

![Image](https://github.com/user-attachments/assets/2f2bfd36-f71e-4f22-8712-68acffa096b7)

**Comment by WalleDAO** [comment]
### **Account Information**  
- **Username:** `walledao`  
- **Registered Email:** 1275511590@qq.com  
- **FID:** 1000990  
- **Account Deletion Time:** April 1, 2025 23:26 to 23:36 UTC  

---

### **Request Details**  
#### 1️⃣ **Primary Request: Full Account Recovery**  
- Complete recovery of my original account with all connections and history  

#### 2️⃣ **Alternative Solution**  
If full recovery is technically impossible:  
- **a) Twitter Unbinding**  
  Unlink my Twitter account@walledao from the deleted profile  
- **b) Username Release**  
  Release the username "walledao" so I can re-register with this name  

---

### **Support History**  
Contacted support@merklemanufactory.com several times but received no response.  

---

### **Attachments**  
1. Figure 1 - The email I used to delete my account  
2. Figure 2 - I tried to recover my account via email  
**System Reply:**  
Farcaster account recovery is not available:
Account does not have a registered FID

<img width="1236" alt="Image" src="https://github.com/user-attachments/assets/4dc427e9-e3ed-46fb-8027-cdb4469d545c" />

<img width="493" alt="Image" src="https://github.com/user-attachments/assets/6f643bbb-b79b-4445-887b-003ff1114583" />
